# Generated by Django 3.0 on 2021-05-10 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccinated',
            name='adhar',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='vaccinated',
            name='mobile',
            field=models.IntegerField(),
        ),
    ]
